### ISSUE TITLE
Error "creation-failed" and detail "failed to retrieve scanner stack"

### ISSUE THREAD

**Issue by ayelencasamassa** [trendmicro/cloudone-filestorage-deployment-templates#140]
I've used those ARM templates to create Terraform manifests for both scanner and storage stacks.
After creating scanner resources, when I try to add the scanner to TM FSS Portal, I get this error:

{
    "stackID": "***",
    "status": "creation-failed",
    "statusDetail": "failed to retrieve scanner stack",
    "details": {}
}

**Comment by trend-jack-c-tang** [comment]
Hi @ayelencasamassa,
When adding the stacks to TM FSS, TM FSS retrieves the required information from ARM deployment outputs. Stacks deployed through Terraform would make FSS unable to get those information, so the requests would fail.

**Comment by ayelencasamassa** [comment]
Can you tell me which info is looking for? TM FSS will always look for a ARM deployment object?

**Comment by trend-jack-c-tang** [comment]
> Can you tell me which info is looking for? TM FSS will always look for a ARM deployment object?

Yes, TM FSS looks for the latest resource group's deployment whose outputs contain the key `scannerStackResourceGroupID`. Then FSS retrieves all the deployment's outputs, when receiving the creating stack request of that particular resource group (FSS stack). In theory, FSS might be able to accept an ARM deployment that provides all the outputs defined in the official ARM templates, but it's not tested and not guaranteed.

**Comment by trend-jack-c-tang** [comment]
I'm afraid you're correct. The product's strategy has been evolved to integrate with Trend Micro Vision One. For [Vision One FSS](https://docs.trendmicro.com/en-us/documentation/article/trend-vision-one-file-security-architecture) it'll be a brand new deployment model that integrates with a central cloud account management feature. Vision One FSS supports AWS only now. Azure is under planning and might use Terraform as IaC AFAIK.
