### ISSUE TITLE
cfn-nag issues

### ISSUE THREAD

**Issue by richardsonky** [trendmicro/cloudone-filestorage-deployment-templates#92]
when cfn-nag is ran against the template aws/FSS-Scanner-Stack.template this error occurs:

| FAIL FATAL
|
| (<unknown>): found unexpected ':' while scanning a plain scalar at line 228 column 69

Failures count: 1

This happens on all AWS pseudo parameters that are used.  They need to be in double quotes for cfn-nag to not report a failure.  This is important because we are trying to deploy this through Control Tower customizations to member accounts and it runs through a cfn-nag validation before it deploys.  We've had to modify these pseudo parameters to pass the scan:

!Ref AWS::NoValue
!Ref AWS::StackId

**Comment by felipecosta09** [comment]
Hello ✋🏽 @richardsonky 

I couldn't find this error here, I ran the cfn-nag and had some warnings but not the same results. Could you double-check if you're using the latest version of the template and if there any additional parameter being used in the cfn-nag to scan the template?

@jack-c-tang

**Comment by jack-c-tang** [comment]
`This happens on all AWS pseudo parameters that are used. They need to be in double quotes for cfn-nag to not report a failure.`
Does the tool report any reason to follow this rule? I don't see any advantage to enforce it.

**Comment by chenjill** [comment]
Hi @richardsonky,
I ran the [cfg_nag scan](https://github.com/stelligent/cfn_nag) with the latest [scanner template](https://github.com/trendmicro/cloudone-filestorage-deployment-templates/tree/master/aws) and it didn’t report any failure. Could you share more information and the command/parameters are used?

**Comment by richardsonky** [comment]
it looks like aws control tower customizations is currently using an old version to scan (0.7.2).  i'll contact support to try and get it upgraded.  thanks for checking.
